MVCBasicsAssignment1/Models/FeverUtillity.cs
using System;
namespace MVCBasicsAssignment1.Models

{
    public class FeverUtillity
    {
        private static double temperature;
        private static string feverStatus;

        public FeverUtillity()
        {

        }
        public FeverUtillity(string temp) {
            double number;
            if(Double.TryParse(temp, out number))
        {
            temperature = Double.Parse(temp) ;
        }
            
            feverStatus = FeverStatus();
        
        }


        private static string FeverStatus()
        {
        
           if(temperature < 13)
            {
                return "If your body tempertur is " + temperature + " your dead!";
            }else if(temperature < 28.0)
            {
                return "If your body tempertur is " + temperature + " your have life-threatning hypothermia";
            }else if(temperature <= 32.0)
            {
                return "If your body tempertur is " + temperature + " your have hypothermia";

            }else if(temperature <= 35.0)
            {
                return "If your body tempertur is " + temperature + " your have mild hypothermia";
            }
            else if(temperature <= 37.6)
            {
               
                return "If your body tempertur is " + temperature + " your have no fever";
            }
            else if (temperature <= 38.5)
            {
                
                return "If your body tempertur is " + temperature + " your have mild fever";
            }
            else
            {
                return "If your body tempertur is " + temperature + " your have high fever";
            }
          
        }

        public void SetTempature(string temp)
        {
            double number;
            if (double.TryParse(temp, out number ))
            {
                temperature = number;
            }

            feverStatus = FeverStatus();
           
        }

        public string GetFever()
        {
            return feverStatus;
        }

        public void reset()
        {
            temperature = 0;
            feverStatus = null;
        }

    }
}

MVCBasicsAssignment1/Models/InfoService.cs
using System.Collections.Generic;

namespace MVCBasicsAssignment1.Models
{
    public class InfoService
    {

        static string about;
        string[] contact;
        static List<string[]> gitHubLinks;
        

        public InfoService()
        {
            
            gitHubLinks = new List<string[]>();
           
            about = " Hej! Jag heter Jörgen Pettersson och bor i Mörrum";
            contact = new string[] { "Namn: Jörgen Pettersson", "Adress: Östravägen 9", " Ort: Mörrum", "Telefon: 0706329725" };
            string[] gitHubHangman = new string[] { "https://github.com/jorgenpe/Hangman", "Guess a word or character" };
            string[] gitHubSokoban = new string[] { "https://github.com/jorgenpe/Sokoban", " Push block to green area by using arrow keys" };

            gitHubLinks.Add(gitHubSokoban);
            gitHubLinks.Add(gitHubHangman);
        }

        public string GetAbout() { return about; }  

        public string[] GetContact() { return contact;}

        public List<string[]> GetGitHubLinks() { return gitHubLinks;}
    }
}

MVCBasicsAssignment1/Models/RandomNumberGame.cs
using System;
namespace MVCBasicsAssignment1.Models
{
    public class RandomNumberGame
    {
        private static string randomNumber;
        private Random random = new Random();

        public RandomNumberGame()
        {
            randomNumber = random.Next(1,101).ToString();
        }

        public string GetRandomNumber()
        {
            return randomNumber;
        }
         public void SetRandomNumber() { randomNumber = random.Next(1, 101).ToString(); }
    
    }
}

MVCBasicsAssignment1/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCBasicsAssignment1.Models;
namespace MVCBasicsAssignment1.Controllers
{
    public class DoctorController : Controller
    {

        FeverUtillity _feverUtillity;

        public DoctorController()
        {
            _feverUtillity = new FeverUtillity();
        }

        public IActionResult Index()
        {
            
            ViewBag.CheckFever = _feverUtillity.GetFever();
            return View();
        }

        [HttpGet]  
        public IActionResult CheckFever()
        {
            ViewBag.CheckFever = _feverUtillity.GetFever();
            return View();
        }

        [HttpDelete]
        public IActionResult DeleteCheckFever()
        {
            ViewData.Clear();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult CheckFever(string fever)
        {
            try
            {
                _feverUtillity.SetTempature(fever);

                return RedirectToAction("Index"); 

            }catch (ArgumentException exData)
            {
                ViewBag.ExceptionMsg = exData.Message;
            }

            ViewBag.Fever = fever;
            ViewBag.CheckFever = _feverUtillity.GetFever();

            return ViewBag();
        }
    } 
}

MVCBasicsAssignment1/Controllers/GameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCBasicsAssignment1.Models;
namespace MVCBasicsAssignment1.Controllers
{
    public class GameController : Controller
    {
        
        RandomNumberGame randomNumber;
        public GameController()
        {
            randomNumber = new RandomNumberGame();
        }
        
        [HttpGet]
        public IActionResult GuessGame()
        {
             
            string randomGame = HttpContext.Session.GetString("GuessGames");
            if (randomGame != null)
            {

                string[] randomGameArray = (randomGame as string).Split('|');

                if(randomGame == "Victory")
                {
                    HttpContext.Session.Clear();
                }
                else if (randomGameArray.Length > 1 && randomGameArray[0] == randomGameArray[randomGameArray.Length - 1])
                {

                    HttpContext.Session.Clear();
                    ViewBag.GuessGames = "Victory";

                }
                else if (randomGame != null)
                {
                    ViewBag.GuessGames = randomGame;
                }
            }
           

            return View();
        }

        [HttpPost]
        public IActionResult GuessGame(string guessGame)
        {
            try { 
                if(!string.IsNullOrWhiteSpace(guessGame))
                {
                    string randomGame = HttpContext.Session.GetString("GuessGames");

                    if(randomGame == null)
                    {
                        string random = randomNumber.GetRandomNumber();
                        HttpContext.Session.SetString("GuessGames", random + '|'+ guessGame);
                    
                    }
                    else
                    {
                        randomGame += '|' + guessGame;
                        HttpContext.Session.SetString("GuessGames", randomGame);
                    }
                }
            }
            catch (ArgumentException exData)
            {
                ViewBag.ExceptionMsg = exData.Message;
            }

            return RedirectToAction(nameof(GuessGame));
        }
    }
}

MVCBasicsAssignment1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCBasicsAssignment1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCBasicsAssignment1/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using MVCBasicsAssignment1.Models;
namespace MVCBasicsAssignment1.Controllers
{
    public class InfoController : Controller
    {
        InfoService _infoService;

        public InfoController()
        {
            _infoService = new InfoService();
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Info = _infoService;
            return View();
        }

        [HttpGet]
        public IActionResult About()
        {
            ViewBag.About = _infoService.GetAbout();
            return View();
        }
        [HttpGet]
        public IActionResult Contact()
        {
            ViewBag.Contact = _infoService.GetContact();
            return View();
        }
        [HttpGet]
        public IActionResult GitHubLinks()
        {
            ViewBag.GitHubLinks = _infoService.GetGitHubLinks();
            return View();
        }


    }
} 

MVCBasicsAssignment1/Views/Doctor/CheckFever.cshtml
@{
    ViewData["Title"] = "FeverCheck - CheckFever";
}

<h1>Check fever</h1>

@if (ViewBag.ExceptionMsg != null)
{
    <h4 class="danger">@ViewBag.ExceptionMsg</h4>
}

<form asp-action="CheckFever" method="post">
    <label for="Fever">Fever: </label>
    <input type="number" step="0.1" name="fever" id="fever" value="@ViewBag.Fever"  />
    <button type="submit">Check fever</button>

</form>

MVCBasicsAssignment1/Views/Doctor/Index.cshtml
@{
    ViewData["Title"] = "FeverCheck - Index";
}

<h1>Check Fever</h1>



<a asp-action="CheckFever">Check Fever</a>


<p asp-action="CheckFever" method="get">@ViewBag.CheckFever</p>

MVCBasicsAssignment1/Views/Game/GuessGame.cshtml
@{
    ViewData["Title"] = "Guessing game";
}

<h1>Guessing game</h1>


@if (ViewBag.ExceptionMsg != null)
{
    <h4 class="danger">@ViewBag.ExceptionMsg</h4>
}

<form asp-action="GuessGame" method="post">
    <input type="number" name="guessGame" value="" step="1" min="1" max="100" placeholder="Guess number between 1-100" />
    <input type="submit"  value="Guessing game" />
</form>

<ul>
    @if (ViewBag.GuessGames != null && ViewBag.GuessGames is string)
    {
        string[] guessGameArray = (ViewBag.GuessGames as string).Split('|');

        if(guessGameArray[0] == "Victory")
        {
            <li>
                <p> You are victorious</p>
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("GuessGame", "Game")'" >Reset Game</button> 
            </li>
        } 
        else{
            for (int i = 1; i < guessGameArray.Length; i++)
            {
                if(int.Parse(guessGameArray[0]) < int.Parse(guessGameArray[i]))
                {
                    <li>
                        <p>@guessGameArray[i] is the wrong number. The number is lower.</p>
                        
                    </li>
                }
                else
                {
                    <li>
                        <p>@guessGameArray[i] is the wrong number.The number is higher.</p>
                        
                    </li>   
                }  

            }
            <li>
                <p>Please guess a new number between 1-100!</p>
            </li>
        }
    }
    else
    {
        <li><p>Please guess a number!</p></li>
    }
</ul>

MVCBasicsAssignment1/Views/Home/Index.cshtml
@{
    ;
    ViewData["Title"] = "Index";
}
<h1>My info page</h1>

MVCBasicsAssignment1/Views/Info/About.cshtml
@{
    ViewData["Title"] = "Info - Information";
}
<h3>About me!</h3>

<p>@ViewBag.About</p>

MVCBasicsAssignment1/Views/Info/Contact.cshtml
@{
    ViewData["Title"] = "Info - Information";
}
<h3>My contact infomation</h3>





       
            <ul>
                <li>@ViewBag.Contact[0]</li>
                <li>@ViewBag.Contact[1]</li>
                <li>@ViewBag.Contact[2]</li>
                <li>@ViewBag.Contact[3]</li>
                
            </ul>
        

MVCBasicsAssignment1/Views/Info/GitHubLinks.cshtml
@{
    ViewData["Title"] = "Info - Information";
}
<h3>My GitHub Links</h3>

<table>
    
    <tbody>
        @foreach (string[] gitHubLink in ViewBag.GitHubLinks)
        {
            <tr>
                <td>
                    <a href="@gitHubLink[0]" >@gitHubLink[0]</a>
                </td>
            </tr>
            <tr>
                <td>@gitHubLink[1]</td>
            </tr>
        }
    </tbody>
</table>

MVCBasicsAssignment1/Views/Info/Index.cshtml
@{
    ViewData["Title"] = "Info - Index";
}
<h1>Info</h1>
<nav>
    <ol>
        <li>
            <a asp-action="About">About me!</a>
        </li>
        <li>
            <a asp-action="Contact">My contact infomation</a>
        </li>
        <li>
            <a asp-action="GitHubLinks">My github links with descriptions</a>
        </li>
    </ol>
</nav>

MVCBasicsAssignment1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <h3>Logo</h3>
        <nav>
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index" >Home</a>
                </li>
                <li>
                    <a asp-controller="Info" asp-action="Index" >Info</a>
                </li>
                <li>
                    <a asp-controller="Doctor" asp-action="Index" >FeverCheck</a>
                </li>
                <li>
                    <a asp-controller="Game" asp-action="GuessGame" >GuessGame</a>
                </li>
            </ul>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    
     <footer>
        <p>&copy; Jörgen P.   @DateTime.Now.ToShortDateString() @DateTime.Now.ToShortTimeString()  </p>
        
    
    </footer>
</body>
</html>